Added IDXSTR for selective execution of runs when completed have been archived

diff --git a/scripts/local/wavi_ensemble b/scripts/local/wavi_ensemble
--- a/scripts/local/wavi_ensemble
+++ b/scripts/local/wavi_ensemble
@@ -40,7 +40,22 @@ sed -r \
 
 until check_timeout_statuses "${ENSEMBLE_NAME}-*"; do
   echo "Running another ensemble, individual runs timed out"
-  model_ensemble -p -v ${ENSEMBLE_CONFIG} $ENSEMBLE_TARGET
+  IDXSTR=""
+  
+  if [ $( find cases/${ENSEMBLE_NAME}-* -maxdepth 1 -name 'execute_command.*.*.log' | wc -l ) -gt 0 ]; then
+    IDXSTR=$( for F in $( find cases/${ENSEMBLE_NAME}-* -maxdepth 2 -name 'driver.jl' 2>/dev/null | egrep '/run/driver.jl$' ); do echo -n ${F/cases\/${ENSEMBLE_NAME}-/} | sed -r 's/^([0-9]+)\/.+$/\1/'; echo -n ","; done )
+    IDXSTR=${IDXSTR%,}
+
+    [ ! -z "$IDXSTR" ] && IDXSTR="-k $IDXSTR"
+    echo "Providing indexes $IDXSTR"
+
+    if [ ${#IDXSTR} -gt 4096 ]; then
+      echo "Logic failure, indexes too long, contact dev: ${#IDXSTR}"
+      exit 1
+    fi
+  fi
+
+  model_ensemble -p $IDXSTR -v ${ENSEMBLE_CONFIG} $ENSEMBLE_TARGET
 done
 
 exit $?
